name: "JFrog OIDC Token Test"
on:
  workflow_dispatch:

permissions:
  id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4.6.1
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
        with:
          oidc-provider-name: github-oidc

      - name: Run JFrog CLI commands
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
        run: |
          # Test the connection
          jf rt ping

          # Test Scope
          jf rt curl -s /access/api/v1/projects | jq -r '.[].project_key' | sort -u
          