name: "JFrog Docker Scan Example"

on:
  workflow_dispatch:    # Manual trigger

permissions:
  id-token: write      
  contents: read   
  security-events: write

jobs:
  jfrog-scan-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_PROJECT: ssc-fsdh
        with:
          oidc-provider-name: github-oidc

      - name: Pull the “test container” Docker image
        run: |
          docker pull ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest

      - name: Run JFrog CLI commands
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_PROJECT: ssc-fsdh
        run: |
          # Test the connection
          jf rt ping

          # (Optional) Collect build environment variables
          jf rt bce

          # (Optional) Collect VCS details from git
          jf rt bag

      - name: Scan “test container” image with JFrog Xray
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_PROJECT: ssc-fsdh
        run: |
          jf docker scan "ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest" --vuln  --fail=false
