name: "JFrog Docker Scan Example"

on:
  workflow_dispatch:    # Manual trigger

permissions:
  id-token: write      
  contents: read   
  security-events: write

jobs:
  scan-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          # If you use project‑scoped identity mappings, uncomment and set:
          # JF_PROJECT: ssc-fsdh
        with:
          oidc-provider-name: github-oidc

      - name: Pull the “test container” Docker image
        run: |
          docker pull ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest
          
      - name: Run JFrog CLI commands
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
        run: |
          # Test the connection
          jf rt ping

          # (Optional) Collect build environment variables
          jf rt bce

          # (Optional) Collect VCS details from git
          jf rt bag

      - name: Scan “test container” image with JFrog Xray
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
        run: |
          # This command asks JFrog Xray to scan the local "hello-world:latest" image
          #jf xray scan docker "ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest"
          #jf rt xray "ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest" --fail-fast --output json
          jf docker scan --format=json "ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest"
