name: "JFrog Docker Scan Example"

on:
  workflow_dispatch:    # Manual trigger
  push:                # Or trigger on any push

permissions:
  id-token: write      # Needed to let jfrog/setup-jfrog-cli fetch an OIDC token
  contents: read       # Needed for actions/checkout

jobs:
  scan-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          # If you use project‑scoped identity mappings, uncomment and set:
          # JF_PROJECT: ssc-fsdh
        with:
          oidc-provider-name: github-oidc

      - name: Pull the “hello-world” Docker image
        run: |
          docker pull ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest

      - name: Scan “container” image with JFrog Xray
        run: |
          # This command asks JFrog Xray to scan the local "hello-world:latest" image
          jf xray scan docker "ghcr.io/fsdh-pfds/ado-az-tf-pwsh-runner:latest"

